url: https://blog.nafis1.my.id
title: "Nafis' Blog"
description: "Thanks for visiting!"
author: "mnafisalmukhdi1"

plugins:
  - jekyll-feed

permalink: /:title
paginate: 20
paginate_path       : /page/:num

collections:
  posts:
    output          : true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
